# Generated by Django 2.0.5 on 2018-05-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='web_info',
            name='web_update',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='web_info',
            name='web_date',
            field=models.DateField(verbose_name='日期'),
        ),
    ]
