# Generated by Django 2.0.5 on 2018-05-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20180507_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='web_info',
            name='web_baidu_today_recory',
            field=models.IntegerField(default=0, verbose_name='百度当天收录'),
        ),
        migrations.AlterField(
            model_name='web_info',
            name='web_ip_pc',
            field=models.IntegerField(default=0, verbose_name='pc_ip'),
        ),
        migrations.AlterField(
            model_name='web_info',
            name='web_ip_phone',
            field=models.IntegerField(default=0, verbose_name='手机ip'),
        ),
    ]
